tap "caskroom/cask"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"

# tap 'nonrational/puma'
# brew 'nonrational/puma/puma-dev'

brew "autojump"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "coreutils"
brew "figlet"
brew "findutils"
brew "fswatch"
brew "gettext"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "goenv"
brew "heroku/brew/heroku"
brew "hub"
brew "netcat"
brew "node-build"
brew "nodenv"
brew "openssl"
brew "parallel"
brew "pyenv"
brew "rbenv"
brew "rclone"
brew "readline"
brew "rename"
brew "ruby-build"
brew "shellcheck"
brew "wget"
brew "xz"

cask "1password"
cask "appcleaner"
cask "audiobookbinder"
cask "bartender"
cask "brave-browser"
cask "calibre"
cask "divvy"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "skitch"
cask "slack"
cask "spotify"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "ticktick"
cask "vlc"
cask "vox"
cask "wavebox"
cask "windscribe"

