tap "caskroom/cask"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "bymealpal/puma"

brew "autojump"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bymealpal/puma/puma-dev"
brew "coreutils"
brew "figlet"
brew "findutils"
brew "fswatch"
brew "gettext"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "heroku/brew/heroku"
brew "hub"
brew "memcached", restart_service: true
brew "netcat"
brew "node-build"
brew "nodenv"
brew "openssl"
brew "parallel"
brew "pyenv"
brew "rbenv"
brew "readline"
brew "rename"
brew "ruby-build"
brew "shellcheck"
brew "wget"
brew "xz"

cask "1password"
cask "appcleaner"
cask "bartender"
cask "boostnote"
cask "brave"
cask "calibre"
cask "copyclip" # copyclip 2 - paid
cask "divvy"
cask "dropbox"
# cask "droplr"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "karabiner-elements" # make caps behave like esc
cask "licecap" # record gifs
cask "skitch"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "sublime-merge"
cask "vox"
cask "wavebox"

