#!/bin/bash

# vars
# src=/etc/apache2/extra/httpd-vhosts.conf
# trg=/etc/apache2/extra/httpd-vhosts-static.conf
sudo touch /dev/null
sudo apachectl configtest && sudo apachectl restart
status=$?

if [[ status -ne 0 ]]; then
    echo "Oh Noes.";
else
    echo "Success";
fi
