#!/usr/bin/env ruby
limit = 10
handles = `git branch -a`.split("\n")
  .map { |b| b.split('/')[2] }
  .each_with_object(Hash.new(0)) { |handle, hash| hash[handle] += 1 }
  .each { |author, branch_count| puts "#{author}:#{branch_count}" if branch_count > limit }
