#!/usr/bin/env ruby
limit = 10
handles = `git branch -a`.split("\n").map { |b| b.split('/')[2] }
frequency = handles.each_with_object(Hash.new(0)) { |handle, hash| hash[handle] += 1 }
frequency.each { |k,v| puts "#{k}:#{v}" if v > limit }
