#!/bin/sh

PEMDIR=~/.ssh/aws
chmod 400 $PEMDIR/*

if [[ $# < 2 ]]; then
    echo "Usage: $0 <pem-name> <ip>";
    exit 1
fi

# is it already an ip?
if [[ "$2" =~ [0-9\.]+ ]]; then
    server_ip=$2
else
    server_ip=`nslookup $2 | awk '/Address/ {print $2}' | tail -n1`
fi

if ! ifconfig | grep '172.' > /dev/null 2>&1 && [[ "$server_ip" =~ ^10\.[01]+\. ]]; then
    echo "You must be on the VPN, kemosabe."
    exit 1
fi

pemfile=$1
shift;shift;

ssh-keyscan -H $server_ip >> ~/.ssh/known_hosts

if [[ $server_ip =~ @ ]]; then
    echo "ssh -i $PEMDIR/$pemfile $server_ip $@"
    ssh -i $PEMDIR/$pemfile $server_ip $@
else
    echo "ssh -i $PEMDIR/$pemfile ec2-user@$server_ip $@"
    ssh -i $PEMDIR/$pemfile ec2-user@$server_ip $@
fi

sed -i'' -e"/$server_ip/d" ~/.ssh/known_hosts
