#!/bin/sh
# easyfirewall.sh
# place in ~/bin/easyfw or somewhere else on your PATH
# you can create a wrapper script that will invoke this one with on, and add it to login via
# sudo defaults write com.apple.loginwindow LoginHook /path/to/script
# 

sudo touch /dev/null

if [ "$1" == "on" -o "$1" == "up" ]; then
    if sudo ipfw show | grep 127.0.0.1,8443 > /dev/null; then
        echo "Already enabled!"
    else
        echo "Mapping 80->8080, 443->8443...";
        sudo ipfw add 101 fwd 127.0.0.1,8443 tcp from any to any 443 in;
        sudo ipfw add 100 fwd 127.0.0.1,8080 tcp from any to any 80 in;
    fi
elif [ "$1" == "off" -o "$1" == "down" ]; then
    echo "Flushing ipfw tables. This will erase all non-default rules. Please confirm.";
    sudo ipfw flush;
fi

echo "-------------------------------------------------------------------------------";
sudo ipfw show;
echo "-------------------------------------------------------------------------------";
