#!/bin/sh

if [ "" == "$1" ]; then
    echo "Please specify a bettermentdb.sql.gz file.";
    exit 1;
fi

dbname=bettermentdb
echo "Restore to $dbname beginning in 5 seconds..."
sleep 5
mysql -uroot << EOF
    DROP DATABASE $dbname;
    CREATE DATABASE $dbname;
    USE $dbname;
EOF

date

time gzcat $1 | mysql -uroot $dbname;
