#!/bin/bash
# Regenerate home/.pi/agent/AGENTS.md from home/.agents/rules/*.md.
#
# Pi loads exactly one global context file -- ~/.pi/agent/AGENTS.md -- with no
# @-import and no directory glob, so the rules have to be concatenated here
# rather than mirrored per-file the way home/.copilot/instructions does it.
# That makes AGENTS.md a generated artifact: this script rewrites it in place
# locally and fails instead under CI, so a rule rename shows up as a red build
# rather than as guidance that silently stopped reaching pi.
set -eu -o pipefail

DOTS="$(cd "$(dirname "$0")/.." && pwd)"
RULES="$DOTS/home/.agents/rules"
OUT="$DOTS/home/.pi/agent/AGENTS.md"

# A header-only AGENTS.md would look fine and silently ship pi zero rules, so
# refuse to write one.
rule_count="$(find "$RULES" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
if [ "$rule_count" -eq 0 ]; then
    echo "error: no rule files found in $RULES" >&2
    exit 1
fi

generate() {
    cat <<'EOF'
<!-- Generated by scripts/build-pi-agents.sh from home/.agents/rules/*.md. Do not edit. -->

# AGENTS.md

Pi's global instructions. Everything below is a verbatim copy of a rule file in `home/.agents/rules/`, which is the source of truth shared across harnesses -- edit the rule there, then run `make check-pi-agents`.

Machine-specific and private instructions do not belong in this file: it is tracked in a public repo. Put those in `~/.pi/agent/APPEND_SYSTEM.md`, which pi appends to the system prompt and which this repo does not track.
EOF
    while IFS= read -r rule; do
        printf '\n<!-- home/.agents/rules/%s -->\n\n' "$(basename "$rule")"
        cat "$rule"
    done < <(find "$RULES" -maxdepth 1 -name '*.md' | LC_ALL=C sort)
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
generate >"$tmp"

if [ -f "$OUT" ] && cmp -s "$tmp" "$OUT"; then
    echo "home/.pi/agent/AGENTS.md mirrors home/.agents/rules"
    exit 0
fi

if [ -n "${CI:-}" ]; then
    echo "[error] home/.pi/agent/AGENTS.md is out of sync with home/.agents/rules. failing CI." >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"
cat "$tmp" >"$OUT"
echo "[fix] regenerated home/.pi/agent/AGENTS.md. please commit the changes."
