name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./setup-macos.sh

