name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-preferences:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sh 20-install-profile.sh
          sh 30-install-sublime-prefs.sh
          sh 40-install-iterm2-preferences.sh
          sh 50-install-karabiner-preferences.sh
          sh 99-install-osx-prefs.sh

